# Generated by Django 3.2.8 on 2021-10-10 14:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='solution',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='ChallengeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_try', models.DateTimeField(default=datetime.datetime.now)),
                ('last_try', models.DateTimeField(auto_now_add=True)),
                ('attempt_date', models.DateTimeField(default=datetime.datetime.now)),
                ('success', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='challenge.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
